services:
  - name: go-app
    type: web
    env: go
    plan: free
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: "8080"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
